# Generated by Django 4.0.3 on 2022-03-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_sportsmen_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsmen',
            name='category',
        ),
        migrations.AddField(
            model_name='sportsmen',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.category'),
        ),
    ]
