# Generated by Django 4.0.3 on 2022-03-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_sportsmen_category_sportsmen_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsmen',
            name='preview',
            field=models.CharField(blank=True, max_length=630, null=True),
        ),
    ]
